name: multi_instance_handler
description: Detect and handle multiple instances of an application.
version: 1.0.0
homepage: https://github.com/lsegal/flutter_multi_instance_handler

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.0.5
  ffi: ^1.0.0
  win32: ^2.0.5
  uuid: ^3.0.0
